import { useState } from "react";
import { Clock, Download, FileOutput } from "lucide-react";
import { T, fontMono } from "@/theme/tokens";
import { SectionHeading, StatCard, Td, Th, useToast } from "@/components/ui";
import { EXPORTS } from "@/data";
import type { ExportRecord } from "@/types";

export function ExportsView() {
  const notify = useToast();
  const [exportsList, setExportsList] = useState<ExportRecord[]>(EXPORTS);

  const download = (file: ExportRecord) => {
    setExportsList((prev) => prev.map((e) => (e.file === file.file ? { ...e, status: "Downloaded" } : e)));
    notify(`${file.status === "Downloaded" ? "Re-downloading" : "Downloading"} ${file.file}…`);
  };

  return (
    <div className="px-8 py-7">
      <SectionHeading eyebrow="EXPORT MANAGEMENT" title="Generated exports" />
      <div className="flex gap-4 flex-wrap mb-6">
        <StatCard icon={FileOutput} label="Exports this month" value="19" accent={T.brass} />
        <StatCard icon={Download} label="Downloaded" value={String(exportsList.filter((e) => e.status === "Downloaded").length)} accent={T.teal} />
        <StatCard icon={Clock} label="Awaiting download" value={String(exportsList.filter((e) => e.status !== "Downloaded").length)} accent={T.slate} />
      </div>
      <div className="rounded-2xl overflow-hidden" style={{ background: T.card, border: `1px solid ${T.hair}` }}>
        <table className="w-full">
          <thead>
            <tr><Th>Job No.</Th><Th>File name</Th><Th>Template</Th><Th>Generated by</Th><Th>Date</Th><Th>Status</Th><Th></Th></tr>
          </thead>
          <tbody>
            {exportsList.map((e) => (
              <tr key={e.file}>
                <Td mono><span style={{ fontWeight: 600, color: T.ink }}>{e.job}</span></Td>
                <Td mono>{e.file}</Td>
                <Td>{e.type}</Td>
                <Td>{e.by}</Td>
                <Td mono>{e.date}</Td>
                <Td>
                  <span className="px-2.5 py-1 rounded-full text-[11px] font-semibold" style={{ ...fontMono, background: T.tealSoft, color: T.teal }}>
                    {e.status}
                  </span>
                </Td>
                <Td><button onClick={() => download(e)} aria-label={`Download ${e.file}`}><Download size={15} color={T.slateSoft} /></button></Td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
